### ISSUE TITLE
build pluign

### ISSUE THREAD

**Issue by thacuber2a03** [lite-xl/lite-xl-ide#13]
https://github.com/lite-xl/lite-xl-ide/tree/main/plugins/build#build-pluign
![image](https://github.com/user-attachments/assets/a3a24cb4-39d0-4d34-9aa3-0fdded5093f2)
it's the main title, like, bruh

**Comment by adamharrison** [comment]
Lol k, I'll fix

**Comment by adamharrison** [comment]
Fixed with b994770.
