### ISSUE TITLE
scrollbars can't be used

### ISSUE THREAD

**Issue by thacuber2a03** [lite-xl/lite-xl-ide#15]
not sure which component of this is the faulty one, but I'm unable to move through the doc by clicking the scrollbars as they just don't react to any clicks

**Comment by ZavGaro** [comment]
I found that debugger cause it (function `DocView:on_mouse_pressed` in "init.lua").

**Comment by adamharrison** [comment]
Yeah, this has been fixed, I think.

**Comment by adamharrison** [comment]
Please reopen if not fixed.
