### ISSUE TITLE
Bug regarding minimap.lua and the debugger plugin

### ISSUE THREAD

**Issue by PerilousBooklet** [lite-xl/lite-xl-ide#3]
When I have installed (along with other plugins) both minimap.lua and the debugger plugin (without the build plugin and ide.lua), I face the following problem:
> when I try to grab minimap.lua's view box, the mouse cursor instead selects the corresponding line inside the minimap and the editor's caret goes there.

**Comment by PerilousBooklet** [comment]
I'm adding this for reference:
![image](https://github.com/adamharrison/lite-xl-ide/assets/80917080/2fafd90c-d690-41e6-aa13-a4614ec29cc0)

**Comment by adamharrison** [comment]
Should be fixed!

**Comment by BartolomeyKant** [comment]
> Should be fixed!

It's not

**Comment by PerilousBooklet** [comment]
It's probably because the stub hasn't been updated, so the plugin you install is still the old version.
